version: "2"
services:
  elasticsearch:
    image: elasticsearch:2.1.1
    ports:
    - 9200:9200
    volumes:
    - ./esdata:/usr/share/elasticsearch/data
    command:
    - -Des.network.bind_host=0.0.0.0
    network_mode: "host"
  logstash:
    image: logstash:2.1.1
    volumes:
    - ./logstash/conf.d:/etc/logstash/conf.d:ro 
    - ./var/log:/host/var/log:ro
    network_mode: "host"
    command: logstash -f /etc/logstash/conf.d --debug
  kibana:
    image: kibana:4.3.1
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://localhost:9200"
    network_mode: "host"
